# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuiwall < Formula
  desc "CLI wallpaper engine for the terminal"
  homepage "https://github.com/Mug-Costanza/tuiwall"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mug-Costanza/tuiwall/releases/download/v0.1.0/tuiwall_Darwin_x86_64.tar.gz"
      sha256 "de35c2bc5f514c6f7f31ceead79896e932d5e217815f5b00659e91a8250c24a2"

      define_method(:install) do
        bin.install "tuiwall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mug-Costanza/tuiwall/releases/download/v0.1.0/tuiwall_Darwin_arm64.tar.gz"
      sha256 "23a3b92182efffe6254277d6f17d81ac2364686aabcdb859ff1d453ef76c76a0"

      define_method(:install) do
        bin.install "tuiwall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mug-Costanza/tuiwall/releases/download/v0.1.0/tuiwall_Linux_x86_64.tar.gz"
      sha256 "541dd7aa61b5a1961bf383b09696d8c6adb5933af70251a6ae869d61b5cd427f"
      define_method(:install) do
        bin.install "tuiwall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mug-Costanza/tuiwall/releases/download/v0.1.0/tuiwall_Linux_arm64.tar.gz"
      sha256 "3b026ba534d87e0c76b2501f503bf17397e95106608a355b3b26b6e83e96ef1d"
      define_method(:install) do
        bin.install "tuiwall"
      end
    end
  end

  test do
    system "#{bin}/tuiwall --version"
  end
end
